name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Regal
        uses: StyraInc/setup-regal@v1.0.0
        with:
          version: v0.10.0
      - name: Lint Rego
        run: regal lint --format github policy
